#!/usr/bin/env node
/**
 * Pulls the live-session system instruction out of ChakaLive.kt so the browser
 * probe tests the REAL prompt rather than a paraphrase of it.
 *
 * The prompt's size is not incidental to what we are testing — it is ~4.7k
 * tokens, and whether that fits inside the sliding window's target is the whole
 * question. A shortened copy would quietly pass a test the real one fails.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const kt = join(here, "../modules/chaka-hands/android/src/main/java/com/chakamyth/hands/ChakaLive.kt");
const src = readFileSync(kt, "utf8");

const start = src.indexOf("    val sys =");
if (start < 0) throw new Error("could not find `val sys =` in ChakaLive.kt");
// The instruction ends at the blank line before the tool declarations.
const end = src.indexOf("    val decls =", start);
if (end < 0) throw new Error("could not find `val decls =` after the prompt");

const block = src.slice(start, end);

// Each line is a Kotlin string literal, optionally joined with `+`. Anything
// that is not a quoted literal (the goal interpolation, memLabels(), etc.) is
// skipped — those are runtime values, not part of the fixed prompt weight.
const pieces = [];
for (const raw of block.split("\n")) {
  const line = raw.trim();
  const m = line.match(/^"((?:[^"\\]|\\.)*)"\s*\+?$/);
  if (!m) continue;
  pieces.push(
    m[1]
      .replace(/\\n/g, "\n")
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, "\\")
  );
}

const prompt = pieces.join("");
if (prompt.length < 5000) {
  throw new Error(`extracted only ${prompt.length} chars — the parse is wrong`);
}

const out = join(here, "live-probe-prompt.js");
writeFileSync(
  out,
  "// GENERATED by tools/extract-prompt.mjs — do not edit.\n" +
    "// The live-session system instruction, lifted verbatim from ChakaLive.kt.\n" +
    `window.CHAKA_SYS = ${JSON.stringify(prompt)};\n`
);

console.log(`extracted ${prompt.length} chars (~${Math.round(prompt.length / 4)} tokens) -> ${out}`);
